{
 "title": "Restic Backup",
 "tags": [
  "backup",
  "health",
  "restic"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "host", "label": "Hosts", "query": "label_values(host)" },
   { "name": "job_label_name", "label": "Job label name", "query": "job" },
   { "name": "job_label_value", "label": "Job label value", "query": "resticprofile" },
   { "name": "added_to_repo_line", "query": "Added to the repository:" },
   { "name": "added_to_repo_regex_start", "query": ".+repository:" },
   { "name": "size_regex", "query": "(?P<size>[\\d\\.]+ \\w+)" }
  ]
 },
 "panels": [
  {
   "title": "Modified files: count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\r\n  sum_over_time(\r\n    {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"} \r\n      | regexp `Files:\\s+(?P<new>\\d+)\\s+new,`\r\n      | label_format data=\"new\"\r\n      | unwrap new [$__auto]\r\n  )\r\nor\r\n  sum_over_time(\r\n    {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"} \r\n      | regexp `Files:.+ (?P<changed>\\d+)\\s+changed,`\r\n      | label_format data=\"changed\"\r\n      | unwrap changed [$__auto]\r\n  )\r\n) by (data)",
     "legendFormat": "{{data}}"
    }
   ]
  },
  {
   "title": "Finished backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time(\n  {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\n    |= `finished 'backup'`\n    [$__auto]\n)",
     "legendFormat": "backups"
    }
   ]
  },
  {
   "title": "Failed  backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  count_over_time(\n    {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\n        |~ `.+ on profile '.+': exit status \\d+`\n        | regexp `.+ on .+ exit status (?P<status>\\d+)`\n        | status != 0\n        [$__auto]      \n  )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(\n  {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\n      |~ `processed .*files,.+ in \\d+:\\d+`\n      | regexp `processed \\d+ files, \\d+\\.\\d+ \\w+ in (?P<minutes>\\d+):(?P<seconds>\\d+)`\n      | label_format duration=\"{{.minutes}}m{{.seconds}}s\"\n      | drop minutes, seconds\n      | unwrap duration_seconds(duration)\n      [$__auto]\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Modified files: size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\r\n    |= `$added_to_repo_line`\r\n    | regexp `$added_to_repo_regex_start $size_regex`\r\n    | unwrap bytes(size)[$__auto]\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Backup set: total size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\r\n    | regexp `processed \\d+ files, $size_regex`\r\n    | unwrap bytes(size)[$__auto]\r\n)",
     "legendFormat": "{{data}}"
    }
   ]
  },
  {
   "title": "Modified files: percentage of all files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\r\n    |= `Files:`\r\n    | regexp `Files:\\s+(?P<new>\\d+)\\s+new,\\s+(?P<changed>\\d+)\\s+changed,\\s+(?P<unmodified>\\d+)\\s+unmodified`\r\n    | label_format modified=`{{add .new .changed}}`\r\n    | label_format ratio=`{{divf .modified .unmodified}}`\r\n    | drop new, changed, modified, unmodified\r\n    | unwrap ratio [$__auto]\r\n)"
    }
   ]
  },
  {
   "title": "Deduplication & compression ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  {$job_label_name=\"$job_label_value\", host=~\"(${host:pipe})\"}\r\n    |= `$added_to_repo_line`\r\n    | regexp `$added_to_repo_regex_start $size_regex \\((?P<stored>\\d+(\\.\\d+)? \\w+) stored\\)`\r\n    | label_format size=`{{bytes .size}}`, stored=`{{bytes .stored}}`\r\n    | label_format ratio=`{{divf .stored .size}}`\r\n    | drop size, stored\r\n    | unwrap ratio[$__auto]\r\n)",
     "legendFormat": "{{data}}"
    }
   ]
  }
 ]
}